config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'static_pages#home'
  #get the help page and set it's path to /help
  get '/help', to: 'static_pages#help', as: 'help'

  post 'wallets/start_monitoring', to: 'wallets#start_monitoring'
  post 'wallets/stop_monitoring', to: 'wallets#stop_monitoring'

  post 'webhooks/handle_transaction_data', to: 'webhooks#handle_transaction_data'
  put 'webhooks/handle_processed_transaction', to: 'webhooks#handle_processed_transaction'

  namespace :users do
    resource :account, only: [:edit, :update, :show]
  end

end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  #make sure the primary key is a comination of wallet_address and chain
  self.primary_keys = :wallet_address, :chain
  validates :wallet_name, presence: true, length: { maximum: 50 }
  validates :wallet_address, presence: true, length: { maximum: 42 }
  validates :chain, presence: true
  validates :wallet_address, uniqueness: { scope: :chain, message: "Address and chain combination must be unique!" }

  #scopes
  scope :monitored, -> { where(monitoring_status: true) }
  scope :for_user, ->(user_id) { where(user_id: user_id) }

  #custom methods
  def start_monitoring
    puts "Start monitoring function"

    response = WalletMonitoringService.start(wallet_address: wallet_address)
    
    if response[:success]
      update!(monitoring_status: true)
      puts "Monitoring started for wallet #{wallet_address}: #{response[:data]}" 
      { success: true, message: "Monitoring started for wallet #{wallet_address}" }
    else
      Rails.logger.error("Failed to start monitoring service for wallet #{wallet_address}: #{response}")
      { failure: true, error: "Monitoring failed for #{wallet_address}" }
    end
  rescue StandardError => e
    Rails.logger.error("Error from [ app/models/wallet.rb ] starting monitoring service for wallet #{wallet_address}: #{e.message}")
    false
  end


  def stop_monitoring
    WalletMonitoringService.stop(wallet_address: wallet_address).tap do |success|
      if success
        update!(monitoring_status: false)
      else
        Rails.logger.error("Failed to stop monitoring for wallet #{wallet_address}")
      end
    end
  rescue StandardError => e
    Rails.logger.error("Error with stopping monitoring service for wallet #{wallet_address}: #{e.message}")
    false
  end

  def update_pending_transactions(transaction)
    puts "Given transaction: #{transaction}"
    puts "Pending if it's here: #{pending_transactions}"
    current_transactions = pending_transactions ? pending_transactions : []
    puts "Current_transactions: #{current_transactions}"


    current_transactions << transaction

    update!(pending_transactions: current_transactions)

    puts "Updated pending transactions for wallet #{wallet_address}: #{transaction}"
  rescue StandardError => e
    Rails.logger.error("Error updating the pending transactions for #{wallet_address}: #{e.message}")
    false
  end

end

app/controllers/wallets_controller.rb
require('net/http')
require('uri')

class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  # GET /wallets or /wallets.json
  def index
    @wallets = current_user.wallets
    @user = current_user

    @pending_transactions = @wallets.map do |wallet|
      {
        wallet_address: wallet[:wallet_address],
        pending_transactions: wallet[:pending_transactions]
      }
    end

    if @pending_transactions.empty?
      @pending_transactions = nil
    end

    puts "Pending Transactions Hash: " + @pending_transactions.inspect
  end

  # GET /wallets/1 or /wallets/1.json
  def show
    @wallet = Wallet.find(params[:id])
    @pending_transactions = @wallet.pending_transactions
    puts "Wallet: #{@wallet.inspect}"
    puts "pending transactions: #{@pending_transactions.inspect}"
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
    @user = current_user
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets or /wallets.json
  def create
    @wallet = current_user.wallets.build(wallet_params)

    puts "Wallet to create: #{@wallet.inspect}"

    if @wallet.chain == 'Withholding'
      current_user.withholding_wallet = @wallet.wallet_address
      if current_user.save
        respond_to do |format|
          
          #we do not need to create a monitoring service for the witholding wallets  
          #redirect to the new wallet
          format.turbo_stream
          format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully created." }
          format.json { render :show, status: :created, location: @wallet }
        end
      else

        Rails.logger.error "User save failed: #{current_user.errors.full_messages.join(', ')}"

        respond_to do |format|
          format.html do
            flash.now[:alert] = "Failed to save user: #{current_user.errors.full_messages.join(', ')}"
            render :new, status: :unprocessable_entity
          end
          format.json { render json: @wallet.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @wallet.save
          puts("Wallet created successfully!")
          #create a monitoring service for the wallets that are not the witholding wallet
          puts("Starting monitoring service for wallet...")
          if start_monitoring(@wallet)
            puts("Wallet monitoring started successfully!")
            format.turbo_stream
            format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully created." }
            format.json { render :show, status: :created, location: @wallet }
          else
            #handle monitoring service failure
            @wallet.destroy #rollback wallet creation
            puts "Something went wrong.. rolling back wallet creation"
            format.html { redirect_to wallets_url, alert: "Failed to create monitoring process for wallet" }  
            format.json { render json: { error: "Failed to start monitoring service." }, status: :unprocessable_entity }
          end
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @wallet.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy

    #if withholding wallet, remove from user
    if @wallet.wallet_address == current_user.withholding_wallet
      current_user.withholding_wallet = nil
      current_user.save
    end

    
    puts("Stopping monitoring service for #{@wallet}...")
    if stop_monitoring(@wallet)
      puts("Stopped monitoring process for #{@wallet} successfully!")
      puts("Destroying wallet...")
      if @wallet.destroy
        puts("Wallet #{@wallet} destroyed successfully!")

        respond_to do |format|
          format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    else
      format.html { redirect_to wallet_url(@wallet), alert: "Failed to stop monitoring process for wallet" }
      format.json { render json: { error: "Failed to stop monitoring service." }, status: :unprocessable_entity }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id]) rescue nil
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      puts params.inspect
      params.require(:wallet).permit(:wallet_name, :wallet_address, :chain, :percentage)
    end

    def start_monitoring(wallet)
      puts "starting wallet with the private method in the wallets controller."
      wallet.start_monitoring
    rescue StandardError => e
      Rails.logger.error("Failed to start monitoring for wallet #{wallet.wallet_address}: #{e.message}")
      false 
    end

    def stop_monitoring(wallet)
      wallet.stop_monitoring
    rescue StandardError => e
      Rails.logger.error("Failed to stop monitoring for wallet #{wallet.wallet_address}: #{e.message}")
      false
    end
end





#private
#def send_data_to_track_wallet(wallet_to_monitor, withholding_wallet)
#  # Use appropriate HTTP methods and libraries to send data
#  # Example using Net::HTTP:
#  uri = URI.parse(base_url + '/api/wallet_submit')
#  http = Net::HTTP.new(uri.host, uri.port)
#  http.use_ssl = (uri.scheme == 'https') #only use https if specified;
#  request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
#  request.body = { wallet: wallet_to_monitor, withholding_wallet: withholding_wallet }.to_json
#  puts request.body.inspect
#  response = http.request(request)
#
#  # Handle response as needed
#  puts response.body
#end
#
#def send_data_to_stop_tracking_wallet(wallet)
#  # Use appropriate HTTP methods and libraries to send data
#  # Example using Net::HTTP:
#  uri = URI.parse(base_url + '/api/wallet_stop')
#  http = Net::HTTP.new(uri.host, uri.port)
#  http.use_ssl = (uri.scheme == 'https') #only use https if specified;
#  request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
#  request.body = wallet.to_json
#  puts request.body.inspect
#  response = http.request(request)
#
#  # Handle response as needed
#  puts response.body
#end
#
#def get_pending_transactions(current_user)
#    @user_id = current_user.id
#    @user_withholding_wallet = current_user.withholding_wallet
#    uri = URI.parse("#{base_url}/api/pending_transactions/#{@user_id}")
#    http = Net::HTTP.new(uri.host, uri.port)
#    http.use_ssl = (uri.scheme == 'https') #only use https if specified;
#    request = Net::HTTP::Get.new(uri.request_uri)
#    response = http.request(request)
#    @pending_transactions = JSON.parse(response.body)
#
#    puts "Pending Transactions: " + @pending_transactions.inspect
#end
#
#def base_url
#  'http://127.0.0.1:5000'
#  #'https://server.taxolotl.xyz'
#end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_edit_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :wallet_name, style: "display: block" %>
    <%= form.text_field :wallet_name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :wallet_address, style: "display: block" %>
    <%= form.text_field :wallet_address, class: 'form-control'  %>
  </div>

    <% if @user && @user.withholding_wallet.nil? %>
      <div>
        <%= form.label :chain, style: "display: block" %>
        <%= form.select :chain, ["Withholding Wallet"], {}, { :class => 'form-select'} %> 
      </div>
    <% else %>
      <div>
        <%= form.label :chain, style: "display: block" %>
        <%= form.select :chain, ["Ethereum", "Polygon", "Base", "Arbitrum", "Optimism"], {}, { :class => 'form-select'} %>
      </div>
    <% end %>


      <div>
        <%= form.label :percentage, style: "display: block" %>
        <%= form.range_field :percentage, in: 10..50, class: 'form-range', id: 'withhold-percentage', value: wallet.percentage %>
      <span id="withhold-percentage-value"></span>
    </div>


    <div style="margin-top: 2rem;"> 
      <%= form.submit "Update Wallet", class: 'form-control' %>
    </div>
  <% end %>

app/views/wallets/_form.html.erb
<%= form_with(model: wallet, id: "#{dom_id(wallet)}_form", class: 'd-none') do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :wallet_name, style: "display: block" %>
    <%= form.text_field :wallet_name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :wallet_address, style: "display: block" %>
    <%= form.text_field :wallet_address, class: 'form-control'  %>
  </div>

    <% if @user && @user.withholding_wallet.nil? %>
      <div>
        <%= form.label :chain, style: "display: block" %>
        <%= form.select :chain, ["Withholding"], {}, { :class => 'form-select'} %> 
      </div>
    <% else %>
      <div>
        <%= form.label :chain, style: "display: block" %>
        <%= form.select :chain, ["Ethereum", "Polygon", "Base", "Arbitrum", "Optimism"], {}, { :class => 'form-select'} %>
      </div>
    <% end %>

    <% if @user && @user.withholding_wallet.nil? %>
      <div></div>
    <% else %>
      <div>
          <%= form.label :percentage, style: "display: block" %>
          <%= form.range_field :percentage, in: 10..50, class: 'form-range', id: 'withhold-percentage', value: 10 %>
        <span id="withhold-percentage-value">10%</span>
      </div>
    <% end %>

    <div style="margin-top: 2rem;"> 
      <%= form.submit "Create Wallet", class: 'form-control' %>
    </div>
  <% end %>

app/views/wallets/_single_wallet.html.erb
<div class="container wallet">
    <div id="<%= dom_id wallet %>">
        <% if wallet.chain == "Withholding" %>
            <div id="withholding_wallet" class="wallet row">
                <h2>Withholding Wallet</h2>
                <p><%= wallet.wallet_address %></p>
            </div>
        <% else %>
            <div id="<%= wallet.chain %>-wallet" class='single-wallet row'>
                <div class="col-lg-6 col-md-12">
                    <% if wallet.chain == 'Ethereum' %>
                        <%= image_tag "ether-icon.svg", class: "wallet-icon" %>
                    <% elsif wallet.chain == "Polygon" %>
                        <%= image_tag "matic-icon.svg", class: "wallet-icon" %>
                    <% elsif wallet.chain == 'Optimism' %>
                        <%= image_tag "optimism-icon.svg", class: "wallet-icon" %>
                    <% elsif wallet.chain == 'Arbitrum' %>
                        <%= image_tag "arbitrum-icon.svg", class: "wallet-icon" %>
                    <% elsif wallet.chain == 'Base' %>
                        <%= image_tag "base-icon.svg", class: "wallet-icon" %>
                    <% end %>
                </div>
                <div class='col-lg-6 col-md-12'>
                    <p class='wallet-address'><%= wallet.wallet_address %></p>
                </div>
            </div>
            <div id="pending-transactions">
                <% if pending_transactions.nil? or pending_transactions.length == 0 %>
                    <p>No pending transactions</p>
                <% else %>
                    <% pending_transactions.each do |transaction| %>
                            <div class="transaction">
                            <p class="value">Value: <%= transaction["value"] %></p>
                            <button 
                                class="transaction-button" 
                                data-hash="<%= transaction["transaction_hash"] %>" 
                                data-user="<%= transaction["user_id"] %>" 
                                data-withholding_wallet="<%= transaction["withholding_wallet"] %>" 
                                data-transacting_wallet="<%= wallet.wallet_address %>"
                                data-amt="<%= Integer(transaction["value"]) * (wallet.percentage / 100) %>">

                                Process</button>
                        </div>
                    <% end %>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/wallets/_transaction.html.erb
<div id="pending_transactions">
    <% if @pending_transactions.any? %>
        <% @pending_transactions.each do |transaction| %>
            <p><%= transaction['user_withholding_wallet'] %></p>
            <p><%= transaction['amt_to_withhold'] %></p>
            <button
                data-wallet="<%= transaction['user_withholding_wallet'] %>"
                data-amt="<%= transaction['amt_to_withhold'] %>"
                data-hash="<%= transaction['hash'] %>"
                data-user="<%= @user_id %>"
          >Withhold Transaction</button>
        <% end %>
    <% else %>
        <p>No pending transactions</p>
    <% end %>
</div>

app/views/wallets/_wallet.html.erb
<div id="<%= dom_id wallet %>">
  <% if wallet.chain == "Withholding" %>
    <div id="withholding_wallet" class="wallet row">
      <h2>Withholding Wallet</h2>
      <p><%= wallet.wallet_address %></p>
      <%= link_to "Manage Withholding Wallet", wallet %>

    </div>
  <% else %>
    <div id="<%= wallet.chain %>-wallet" class='wallet row'>
      <% count = wallet.pending_transactions.count rescue 0 %>
      <span class="count-notification"><%= count %> Pending Transactions</span>
      <div class='col-lg-6 col-md-12'>
        <div class='chain-id'>
          <% if wallet.chain == 'Ethereum' %>
            <%= image_tag "ether-icon.svg", class: "wallet-icon" %>
          <% elsif wallet.chain == 'Polygon' %>
            <%= image_tag "matic-icon.svg", class: "wallet-icon" %>
          <% elsif wallet.chain == 'Optimism' %>
            <%= image_tag "optimism-icon.svg", class: "wallet-icon" %>
          <% elsif wallet.chain == 'Arbitrum' %>
            <%= image_tag "arbitrum-icon.svg", class: "wallet-icon" %>
          <% elsif wallet.chain == 'Base' %>
            <%= image_tag "base-icon.svg", class: "wallet-icon" %>
          <% end %>
          <h2><%= wallet.chain %> Wallet</h2>
        </div>
        <p class="wallet-address"><%= wallet.wallet_address %></p>
      </div>
      
      <div class='col-lg-6 col-md-12'>
      <%= link_to "View", wallet %>
      </div>
    </div>
  <% end %>
</div>

app/views/wallets/_withholding_edit_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :wallet_name, style: "display: block" %>
    <%= form.text_field :wallet_name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :wallet_address, style: "display: block" %>
    <%= form.text_field :wallet_address, class: 'form-control'  %>
  </div>

    <div style="margin-top: 2rem;"> 
      <%= form.submit "Update Wallet", class: 'form-control' %>
    </div>
  <% end %>

app/views/wallets/create.turbo_stream.erb
<%= turbo_stream.prepend "wallets" do %>
    <%= render "wallet", wallet: @wallet %>
<% end %>
<%= turbo_stream.replace "#{dom_id(Wallet.new)}_form" do %>
    <%= render "form", wallet: Wallet.new, user: @user %>
<% end %>

app/views/wallets/edit.html.erb
<div class="container session-form">
  <h2>Editing wallet</h2>

  <% if @wallet.chain == 'Withholding Wallet' %>
    <%= render "withholding_edit_form", wallet: @wallet %>
  <% else %>
    <%= render "edit_form", wallet: @wallet %>
  <% end %>

  <br>

  <div>
    <%= link_to "Show this wallet", @wallet %> |
    <%= link_to "Back to wallets", wallets_path %>
  </div>
</div>

app/views/wallets/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1>Wallets</h1>
<hr />

<div id="new-wallet-form" class="container session-form">
  <h2>Create New Wallet</h2>
  <%= render 'form', wallet: Wallet.new, user: @user %>
</div>


<div id="wallets">
  <% @wallets.each do |wallet| %>
    <%= render wallet, pending_transactions: @pending_transactions %>
  <% end %>
</div>



</div>

app/views/wallets/new.html.erb
<div class="container session-form">
<h2>New wallet</h2>

<%= render "form", wallet: @wallet, user: @user%>

<br>

<div>
  <%= link_to "Back to wallets", wallets_path %>
</div>
</div>

app/views/wallets/show.html.erb
<div class="container wallet">
  <%= render partial: 'single_wallet', locals: { wallet: @wallet, pending_transactions: @pending_transactions } %>

  <div class="wallet-options">
    <%= link_to "Edit this wallet", edit_wallet_path(@wallet) %>
    <%= link_to "Back to wallets", wallets_path %>

    <%= button_to "Destroy this wallet", @wallet, method: :delete %>
  </div>
</div>