config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'static_pages#home'
  #get the help page and set it's path to /help
  get '/help', to: 'static_pages#help', as: 'help'

  post 'wallets/start_monitoring', to: 'wallets#start_monitoring'
  post 'wallets/stop_monitoring', to: 'wallets#stop_monitoring'

  post 'webhooks/handle_transaction_data', to: 'webhooks#handle_transaction_data'
  put 'webhooks/handle_processed_transaction', to: 'webhooks#handle_processed_transaction'

  namespace :users do
    resource :account, only: [:edit, :update, :show]
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <%= link_to 'Taxolotl', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Help", help_path, class: "nav-link" %>
        </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Account", users_account_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
          <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taxolotl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-refresh-method" content="morph">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Turret+Road:wght@200;300;400;500;700;800&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "custom", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div id='content-wrap' class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ethers/6.13.4/ethers.umd.min.js" integrity="sha512-V3xRGsQMQ8CG4l2gVN44TCDmNY5cdlxbSvejrgmWxcLKHft0Q3XQDbeuJ9aot14mpNuRWGtI//WKraedDGNZ+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    let baseURL
    if (window.location.hostname == 'localhost' || window.location.hostname == '127.0.0.1'){
      baseURL = "http://localhost:3000/webhooks/handle_processed_transaction";
    }else{ 
      baseURL = "https://taxolotl.xyz/webhooks/handle_processed_transaction";
    }
  </script>

</html>